[package]
name = "rsevm"
version = "0.1.0"
authors = ["Thibault H <Aelto@users.noreply.github.com>"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.89", features = ["derive"] }
flame = "0.2.2"
ctrlc = "3.1.3"